import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Guilherme Cardoso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-blue-800">
        <section className="bg-blue-700 h-screen">
          <h1 className="text-3xl font-bold underline">Hello world!</h1>
        </section>
      </main>
    </div>
  );
}
