import Head from "next/head";
import NavBar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Guilherme Cardoso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-blue-700 h-screen">
          <NavBar/>
        </section>
      </main>
    </div>
  );
}
